# Next.js build + deploy on Azure Static Web Apps
trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

  variables:
  - group: Azure-Static-Web-Apps-mango-bush-0a726a800-variable-group

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '24.x'  # match your local version
    displayName: 'Install Node.js 24.x'

  - script: npm ci --include=dev
    displayName: 'Install dependencies (including devDeps)'

  - script: npm run build
    displayName: 'Build Next.js app'
    env:
      NODE_ENV: $(NODE_ENV)

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/"
      api_location: ""
      output_location: ""
    displayName: 'Deploy to Azure Static Web App'
    env:
      azure_static_web_apps_api_token: $(deployment_token)

