name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main

trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  pool:
    vmImage: ubuntu-latest

  variables:
  - group: Azure-Static-Web-Apps-mango-bush-0a726a800-variable-group

  steps:
  - checkout: self
    submodules: true

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BUSH_0A726A800)
      app_location: "."               # Root of your Next.js app
      api_location: ""                # Leave empty (no Azure Functions)
      output_location: ".next"        # Next.js build output directory
