import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sileo";
import { NextStepProvider, NextStep, type Tour } from 'nextstepjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bookufy",
  description: "Generated by create next app",
};

const steps: Tour[] = [
  {
    tour: "bookingTour",
    steps: [
      {
        title: "Select Location",
        content: "Choose the branch or location where you want to book your appointment.",
        selector: "#location-card",
        icon: "📍",
        side: "bottom" as const,
        showSkip: true,
      },
      {
        title: "Select Service",
        content: "Pick the service or procedure you need.",
        selector: "#service-card",
        icon: "💼",
        side: "left" as const,
        showSkip: true,
      },
      {
        title: "Select Professional",
        content: "Choose the professional or staff member you'd like to book with.",
        selector: "#professional-card",
        icon: "👨‍⚕️",
        side: "bottom" as const,
        showSkip: true,
      },
      // {
      //   title: "Select Room",
      //   content: "Pick the room where your appointment will take place.",
      //   selector: "#room-card",
      //   icon: "🏥",
      //   side: "bottom" as const,
      //   showSkip: true,
      // },
    ],
  },
  {
    tour: "bookingTourMobile",
    steps: [
      {
        title: "Select Location",
        content: "Choose the branch or location where you want to book your appointment.",
        selector: "#mobile-location-card",
        icon: "📍",
        side: "bottom" as const,
        showSkip: true,
      },
      {
        title: "Select Service",
        content: "Pick the service or procedure you need.",
        selector: "#mobile-service-card",
        icon: "💼",
        side: "bottom" as const,
        showSkip: true,
      },
      {
        title: "Select Professional",
        content: "Choose the professional or staff member you'd like to book with.",
        selector: "#mobile-professional-card",
        icon: "👨‍⚕️",
        side: "bottom" as const,
        showSkip: true,
      },
      // {
      //   title: "Select Room",
      //   content: "Pick the room where your appointment will take place.",
      //   selector: "#mobile-room-card",
      //   icon: "🏥",
      //   side: "bottom" as const,
      //   showSkip: true,
      // },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextStepProvider>
          <NextStep steps={steps} clickThroughOverlay={true}>
            <Toaster position="top-center" />
            {children}
          </NextStep>
        </NextStepProvider>
      </body>
    </html>
  );
}
